logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO

server:
   port: 9000

# Spring Security configuration
security:
  oauth2:
    client:
      grantType: client_credentials
      clientId: travel-api-client
      clientSecret: psw
      accessTokenUri: http://localhost:8080/oauth/token

airports_url: http://localhost:8080/airports

travel_fare_url: http://localhost:8080/fares

single_airport_url: http://localhost:8080/airports
